#' Create a nicely formatted table from a linear model.
#'
#' Given a general linear model (like from [stats::lm()] or [stats::glm()]) this
#' function makes a table intended for interactive use or publication.
#'
#' @param model A model object that is compatible with [broom::tidy()].
#' @param conf_level The confidence level that will be used for computing the
#' confidence interval.
#' @param digits The number of decimal places that numbers in the table should
#' be rounded to. For no rounding use `Inf`. This argument is provided to
#' [base::round()]. The default value is `2`.
#' @param concat_signif If `TRUE` the resulting data frame will append
#' significance symbols as generated by [toffee_signif()]. Otherwise the
#' significance symbols will appear in a separate column called `Significant`.
#' @param odds_ratio If `TRUE` and the family of the model provided is
#' `logit` then the model coefficients and confidence intervals returned in
#' the resulting table will be odds ratios.
#' @param ... Arguments that will be passed to [toffee_signif]. For example,
#' @return A [tibble::tibble()] with the following columns: the
#' name of the coefficient in the model (`Variable`), the value of the
#' coefficient (`Estimate` or `Odds_Ratio`), the
#' confidence interval for the coefficient (`CI`), the p-value for the term,
#' (`p_value`), and optionally symbols representing levels of significance
#' (`Significant`).
#'
#' @export
#' @importFrom broom tidy
#' @importFrom purrr map_dbl map_chr is_null map2_chr
#' @importFrom dplyr mutate mutate_at select rename "%>%"
#' @examples
#'
#' library(dplyr)
#' library(toffee)
#'
#' set.seed(2017-10-15)
#'
#' tree_data <- trees %>%
#'   mutate(Branches = sample(15:25, size = 31, replace = TRUE)) %>%
#'   mutate(Healthy = Branches > 20) %>%
#'   mutate(Healthy = Healthy + sample(c(0, 1), size = nrow(.), replace = TRUE)) %>%
#'   mutate(Healthy = Healthy > 0)
#'
#' linear_model <- tree_data %>%
#'   lm(Volume ~ Girth + Height + Branches, data = .)
#'
#' # Basic usage
#' linear_model %>%
#'   toffee_tbl()
#'
#'  # # A tibble: 4 x 4
#'  #   Variable    Estimate CI               p_value
#'  #   <chr>          <dbl> <chr>            <chr>
#'  # 1 (Intercept)   -67.2  [-86.81, -47.59] < 0.01***
#'  # 2 Girth           4.75 [4.23, 5.27]     < 0.01***
#'  # 3 Height          0.33 [0.08, 0.59]     0.01*
#'  # 4 Branches        0.46 [-0.03, 0.95]    0.07
#'
#' # Using the `chars` argument from toffee_signif
#' linear_model %>%
#'   toffee_tbl(thresholds = 0.01, chars = "*")
#'
#'  # # A tibble: 4 x 4
#'  #   Variable    Estimate CI               p_value
#'  #   <chr>          <dbl> <chr>            <chr>
#'  #   1 (Intercept)   -67.2  [-86.81, -47.59] < 0.01*
#'  #   2 Girth           4.75 [4.23, 5.27]     < 0.01*
#'  #   3 Height          0.33 [0.08, 0.59]     0.01
#'  #   4 Branches        0.46 [-0.03, 0.95]    0.07
#'
#' # Separating the significance symbols into their own column
#' linear_model %>%
#'   toffee_tbl(concat_signif = FALSE)
#'
#' logistic_model <- tree_data %>%
#'   glm(Healthy ~ Girth + Height + Branches + Volume, data = .,
#'       family = binomial())
#'
#' logistic_model %>%
#'   toffee_tbl()
#'
#' logistic_model %>%
#'   toffee_tbl(thresholds = 0.01, chars = "*")
toffee_tbl <- function(model, conf_level = 0.95, digits = 2,
                       concat_signif = TRUE, odds_ratio = TRUE, ...) {

  link <- model$link
  if(is_null(link)) {
    link <- family(model)$link
  }

  if(link == "logit" && odds_ratio) {
    mean_function <- exp
  } else {
    mean_function <- make.link(link)$linkinv
  }

  result <- tidy(model, conf.int = TRUE, conf.level = conf_level) %>%
    mutate(Significant = toffee_signif(p.value, ...)) %>%
    mutate_at(c("estimate", "conf.low", "conf.high"), mean_function) %>%
    mutate_at(c("estimate", "conf.low", "conf.high", "p.value"),
              round, digits = digits) %>%
    mutate(p.value = map_chr(p.value, as.character)) %>%
    mutate(p.value = map_chr(p.value, ~ if_else(.x < 0.01, "< 0.01", .x))) %>%
    mutate(CI = map2_chr(conf.low, conf.high,
                         ~ paste0("[", .x, ", ", .y, "]"))) %>%
    dplyr::select(term, estimate, CI, p.value, Significant) %>%
    rename(Variable = term, Estimate = estimate, p_value = p.value)

  if(link == "logit" && odds_ratio) {
    result <- result %>%
      rename(Odds_Ratio = Estimate)
  }

  if(concat_signif) {
    result <- result %>%
      mutate(p_value = paste0(p_value, Significant)) %>%
      select(-Significant)
  }

  result
}
